server:
  port: 8080
  servlet:
    context-path: /myapp

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/bookteria_identity"
    username: root
    password: root

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true