server:
  port: 8080
  servlet:
    context-path: /myapp

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/quanpham_secondapp?createDatabaseIfNotExist=true&autoReconnect=true"
    username: root
    password: root
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 50
jwt:
  secretKey: 2afc9dd527ddcece93ade3043128c21459fba23a411a6015f531a326cd67a317
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds
  timeOut: 24
  expiryDay: 14
#  secretKey: abc   0053fe0004fb4e1a65316d5e70f64fe1ec3b455467295960c1f67e7058790c02    2afc9dd527ddcece93ade3043128c21459fba23a411a6015f531a326cd67a317
#  TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=